{application,sport_monks,
             [{config_mtime,1730281178},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,req,jason]},
              {description,"Elixir client for the SportMonks API(v3).\n"},
              {modules,['Elixir.SportMonks','Elixir.SportMonks.Client',
                        'Elixir.SportMonks.Error',
                        'Elixir.SportMonks.Resources.Fixtures',
                        'Elixir.SportMonks.Resources.Leagues',
                        'Elixir.SportMonks.Resources.Livescores',
                        'Elixir.SportMonks.Resources.Seasons',
                        'Elixir.SportMonks.Resources.Teams']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
